In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("data/indian_ecommerce_pricing_revenue_growth_36_months.csv")

In [4]:
df.head()

,order_id,order_date,state,zone,category,brand_type,customer_gender,customer_age,base_price,discount_percent,final_price,units_sold,revenue,sales_event,competition_intensity,inventory_pressure
0,ORD0000001,2023-01-31,West Bengal,East,Fashion,Mass,Male,28,1810.89,65.00,633.81,29,18380.49,Normal,Medium,High
1,ORD0000002,2023-01-31,Gujarat,West,Sports & Fitness,Mass,Male,19,5678.15,50.83,2791.95,67,187060.65,Normal,Medium,High
2,ORD0000003,2023-01-31,Delhi NCR,North,Grocery Essentials,Mass,Male,25,169.98,35.26,110.05,57,6272.85,Normal,Medium,Low
3,ORD0000004,2023-01-31,Madhya Pradesh,Central,Footwear,Mass,Female,30,3244.91,61.94,1235.01,55,67925.55,Normal,High,High
4,ORD0000005,2023-01-31,Haryana,North,Fashion,Premium,Female,33,697.44,48.27,360.79,29,10462.91,Festival,Medium,High

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               30600 non-null  str
 1   order_date             30600 non-null  str
 2   state                  30600 non-null  str
 3   zone                   30600 non-null  str
 4   category               30600 non-null  str
 5   brand_type             30600 non-null  str
 6   customer_gender        30600 non-null  str
 7   customer_age           30600 non-null  int64
 8   base_price             30600 non-null  float64
 9   discount_percent       30600 non-null  float64
 10  final_price            30600 non-null  float64
 11  units_sold             30600 non-null  int64
 12  revenue                30600 non-null  float64
 13  sales_event            30600 non-null  str
 14  competition_intensity  30600 non-null  str
 15  inventory_pressure     30600 non-null  str
dtypes: float64(4), int64(2), str(10)
memory usage: 5.8 MB

In [6]:
df.shape

(30600, 16)

In [7]:
df.columns

Index(['order_id', 'order_date', 'state', 'zone', 'category', 'brand_type',
       'customer_gender', 'customer_age', 'base_price', 'discount_percent',
       'final_price', 'units_sold', 'revenue', 'sales_event',
       'competition_intensity', 'inventory_pressure'],
      dtype='str')

In [8]:
df.describe()

,customer_age,base_price,discount_percent,final_price,units_sold,revenue
count,30600.000000,30600.000000,30600.000000,30600.000000,30600.000000,30600.000000
mean,35.568268,3898.637966,38.111218,2415.015197,31.705490,71062.430294
std,12.872780,3371.290126,16.608485,2264.892146,21.381121,83626.572222
min,18.000000,100.030000,0.010000,35.010000,2.000000,247.800000
25%,25.000000,1314.637500,24.840000,747.010000,16.000000,16689.700000
50%,33.000000,2975.015000,37.290000,1728.605000,27.000000,42138.510000
75%,45.000000,5342.480000,51.840000,3309.630000,42.000000,92589.245000
max,65.000000,14999.170000,65.000000,14682.280000,161.000000,906141.040000

In [9]:
df.isnull().sum()

order_id                 0
order_date               0
state                    0
zone                     0
category                 0
brand_type               0
customer_gender          0
customer_age             0
base_price               0
discount_percent         0
final_price              0
units_sold               0
revenue                  0
sales_event              0
competition_intensity    0
inventory_pressure       0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30600 entries, 0 to 30599
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               30600 non-null  str
 1   order_date             30600 non-null  datetime64[us]
 2   state                  30600 non-null  str
 3   zone                   30600 non-null  str
 4   category               30600 non-null  str
 5   brand_type             30600 non-null  str
 6   customer_gender        30600 non-null  str
 7   customer_age           30600 non-null  int64
 8   base_price             30600 non-null  float64
 9   discount_percent       30600 non-null  float64
 10  final_price            30600 non-null  float64
 11  units_sold             30600 non-null  int64
 12  revenue                30600 non-null  float64
 13  sales_event            30600 non-null  str
 14  competition_intensity  30600 non-null  str
 15  inventory_pressure     30600 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), str(9)
memory usage: 5.6 MB

In [13]:
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()
df['quarter'] = df['order_date'].dt.quarter

In [14]:
df.head()

,order_id,order_date,state,zone,category,brand_type,customer_gender,customer_age,base_price,discount_percent,final_price,units_sold,revenue,sales_event,competition_intensity,inventory_pressure,year,month,month_name,quarter
0,ORD0000001,2023-01-31,West Bengal,East,Fashion,Mass,Male,28,1810.89,65.00,633.81,29,18380.49,Normal,Medium,High,2023,1,January,1
1,ORD0000002,2023-01-31,Gujarat,West,Sports & Fitness,Mass,Male,19,5678.15,50.83,2791.95,67,187060.65,Normal,Medium,High,2023,1,January,1
2,ORD0000003,2023-01-31,Delhi NCR,North,Grocery Essentials,Mass,Male,25,169.98,35.26,110.05,57,6272.85,Normal,Medium,Low,2023,1,January,1
3,ORD0000004,2023-01-31,Madhya Pradesh,Central,Footwear,Mass,Female,30,3244.91,61.94,1235.01,55,67925.55,Normal,High,High,2023,1,January,1
4,ORD0000005,2023-01-31,Haryana,North,Fashion,Premium,Female,33,697.44,48.27,360.79,29,10462.91,Festival,Medium,High,2023,1,January,1

In [15]:
df['total_cost'] = df['base_price'] * df['units_sold']

In [16]:
df['total_sales'] = df['final_price'] * df['units_sold']

In [17]:
df['discount_amount'] = df['base_price'] - df['final_price']

In [18]:
df.head()

,order_id,order_date,state,zone,category,brand_type,customer_gender,customer_age,base_price,discount_percent,...,sales_event,competition_intensity,inventory_pressure,year,month,month_name,quarter,total_cost,total_sales,discount_amount
0,ORD0000001,2023-01-31,West Bengal,East,Fashion,Mass,Male,28,1810.89,65.00,...,Normal,Medium,High,2023,1,January,1,52515.81,18380.49,1177.08
1,ORD0000002,2023-01-31,Gujarat,West,Sports & Fitness,Mass,Male,19,5678.15,50.83,...,Normal,Medium,High,2023,1,January,1,380436.05,187060.65,2886.20
2,ORD0000003,2023-01-31,Delhi NCR,North,Grocery Essentials,Mass,Male,25,169.98,35.26,...,Normal,Medium,Low,2023,1,January,1,9688.86,6272.85,59.93
3,ORD0000004,2023-01-31,Madhya Pradesh,Central,Footwear,Mass,Female,30,3244.91,61.94,...,Normal,High,High,2023,1,January,1,178470.05,67925.55,2009.90
4,ORD0000005,2023-01-31,Haryana,North,Fashion,Premium,Female,33,697.44,48.27,...,Festival,Medium,High,2023,1,January,1,20225.76,10462.91,336.65

In [19]:
df.to_csv("data/cleaned_ecommerce_data.csv", index=False)